### PR TITLE
add ability for multiple secrets

### LINKED ISSUE #13: Update init container to support multiple secrets
Presently, the init container is designed to fetch 1 secret from AWS Secrets Manager, yet some pods may require multiple secrets.  The annotation for secretArn should accept an array that the init container can loop through to get multiple secrets. Need to decide whether to mount each secret as a separate volume, write to separate files on the same volume, or create a single file with K/V pairs for each secret.

### PR DESCRIPTION
**Pull request by danquack**
*Issue #, if available:* closes #13 

*Description of changes:*

- Changed the secret path to mount at `/tmp/secrets/<secret name>`
- Added test for aws-secrets-manager

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by danquack** [comment]
If you think a different name is better that's cool too. Just try to keep it as minimal as possible, but open to suggestions if you want.

**Comment by jicowan** [comment]
I need to think about it.  I opened an issue (help wanted) for a user defined file name.  That would probably be the best thing here.  The developer could specify it as another (optional) annotation.

**Comment by danquack** [comment]
Would you expect that as acceptance criteria for this issue, or a future request

**Comment by jicowan** [comment]
@danquack No, I don't think the user-defined filename is required to accept this PR.  We can handle that separately.  That said, I would like to create a separate branch for the multiple secrets, at least until we've pushed the code for the controller that handles the rotation of secrets.  Thanks for your work on this.

**Comment by danquack** [comment]
@jicowan can you let me know what branch you want me to send this to then instead?

**Comment by jicowan** [comment]
@danquack I created a branch called multi-secret.

**Comment by danquack** [comment]
Reopened as #22

**Comment by ranmeekkhsc** [comment]
is admission controller able to handle Secret_ARN as array as of now ?

**Comment by jicowan** [comment]
@danquack created a separate branch that allows you to reference multiple secrets. We will likely merge it into the mainline after releasing the logic for rotating secrets.

**Pull request closed without merging**
