### PR TITLE
Multiple secrets

### LINKED ISSUE #13: Update init container to support multiple secrets
Presently, the init container is designed to fetch 1 secret from AWS Secrets Manager, yet some pods may require multiple secrets.  The annotation for secretArn should accept an array that the init container can loop through to get multiple secrets. Need to decide whether to mount each secret as a separate volume, write to separate files on the same volume, or create a single file with K/V pairs for each secret.

### PR DESCRIPTION
**Pull request by danquack**
*Issue #, if available:* Closes #13 

*Description of changes:*

- Changed the secret path to mount at `/tmp/secrets/<secret name>`
- Added test for aws-secrets-manager

 cc @jicowan 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dnascimento** [comment]
@danquack  @jicowan  can we consider merging to master? The sooner the best as users will create dependencies on /tmp/secret structure

**Comment by sanketgawade** [comment]
@danquack I am also waiting for this to be merged to master, as this will help us a lot to manager secrets in EKS Cluster.

**Comment by danquack** [comment]
I don't maintain this repo, this change that I opened, to a branch vs master, was at the recommendation of the maintainers.

**Comment by omriarieli** [comment]
Hi, how do i reference multiple secrets?

**Comment by dnascimento** [comment]
Hi @omriarieli , please checkout the branch: "multi-secret": https://github.com/aws-samples/aws-secret-sidecar-injector/tree/multi-secret#accessing-the-secret 

With that code, you can refer multiple-secrets by separating them with commas

**Comment by omriarieli** [comment]
Hi @dnascimento, thanks for the reply is there a docker image for this branch? i cloned the repo in this branch theres a helm folder but trying to install getting 
`Failed to pull image "docker.io/amazon/aws-secrets-manager-secret-adm-controller:0.2": rpc error: code = Unknown desc = Error response from daemon: manifest for amazon/aws-secrets-manager-secret-adm-controller:0.2 not found: manifest unknown: manifest unknown`

docker hub has v0.1.1 and v0.1.2 are any of them built from multi-secret branch?
thanks
Omri

**Comment by omriarieli** [comment]
Hi, thanks for the reply. i have built the images from multi-secret branch and installed the helm chart using these images. i see the annotations in the pod's manifest and init container has run and complete, yet under /tmp inside the container there is nothing. i have tried with two secrets seperated by a "," and with one secret as well. if you need any more info i would be happy to provide. using same service account that has the needed iam policy and verified as working from master branch with one secret.

Thanks
Omri

**Comment by dnascimento** [comment]
Could you share your configuration and logs @omriarieli so that I can help to debug? Feel welcomed to send me an email

**Comment by omriarieli** [comment]
Hi, I just noticed in my pod's generated manifest that both secrets get mounted not in /tmp/secrets that was my confusion. actually both secrets are present under /secrets

    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kubernetes-external-secrets-token-69hjp
      readOnly: true
    - mountPath: /secrets/my-env/my-secret-1
      name: secret-vol
      readOnly: true
      subPath: secrets/my-env/my-secret-1
    - mountPath: /secrets/my-env/my-secret-2
      name: secret-vol
      readOnly: true
      subPath: secrets/my-env/my-secret-2

thanks

**Pull request merged**
